apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  # the data is abbreviated in this example
  database: cG9sbHM=
  username: amVmZndheW5lMjU2
  password: c2VrcmV0MQ==
