apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.secrets.name }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.application.secrets.key }}
  DB_USERNAME: {{ .Values.application.secrets.username }}
  DB_PASSWORD: {{ .Values.application.secrets.password }}
