apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secrets.name }}
type: Opaque
data:
  database: {{ .Values.application.secrets.database }}
  username: {{ .Values.application.secrets.username }}
  password: {{ .Values.application.secrets.password }}
